# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from server import gesture_pb2 as gesture__pb2


class GestureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectHand = channel.unary_unary(
                '/gesture.GestureService/DetectHand',
                request_serializer=gesture__pb2.ImageRequest.SerializeToString,
                response_deserializer=gesture__pb2.DetectionResponse.FromString,
                )


class GestureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectHand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectHand': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectHand,
                    request_deserializer=gesture__pb2.ImageRequest.FromString,
                    response_serializer=gesture__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gesture.GestureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GestureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectHand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gesture.GestureService/DetectHand',
            gesture__pb2.ImageRequest.SerializeToString,
            gesture__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
