# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gesture.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgesture.proto\x12\x07gesture\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"&\n\x11\x44\x65tectionResponse\x12\x11\n\tlandmarks\x18\x01 \x03(\x02\x32Q\n\x0eGestureService\x12?\n\nDetectHand\x12\x15.gesture.ImageRequest\x1a\x1a.gesture.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gesture_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=55
  _globals['_DETECTIONRESPONSE']._serialized_start=57
  _globals['_DETECTIONRESPONSE']._serialized_end=95
  _globals['_GESTURESERVICE']._serialized_start=97
  _globals['_GESTURESERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
